version: '3'

tasks:
  build:
    cmds:
      - go build -o bin/sharedclipboard cmd/shared-clipboard/main.go

  build-linux:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o bin/sharedclipboard cmd/shared-clipboard/main.go

  build-windows:
    cmds:
      - GOOS=windows GOARCH=amd64 go build -o bin/sharedclipboard.exe cmd/shared-clipboard/main.go

  build-macos:
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -o bin/sharedclipboard cmd/shared-clipboard/main.go

  clean: 
    cmds:
      - rm -rf bin

  install:
    cmds:
      - task: build
      - cp bin/sharedclipboard /usr/local/bin/sc
      - chmod +x /usr/local/bin/sc
      - task: clean
